### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'pydantic._internal'

### ISSUE THREAD

**Issue by stolenvw** [Russell-Newton/TikTokPy#52]
Getting this with version 0.2.0.post1

```
from tiktokapipy.async_api import AsyncTikTokAPI

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/django-test/.venv/lib/python3.10/site-packages/tiktokapipy/async_api.py", line 14, in <module>
    from tiktokapipy.api import TikTokAPI
  File "/home/user/django-test/.venv/lib/python3.10/site-packages/tiktokapipy/api.py", line 15, in <module>
    from tiktokapipy.models.challenge import Challenge
  File "/home/user/django-test/.venv/lib/python3.10/site-packages/tiktokapipy/models/__init__.py", line 12, in <module>
    from pydantic._internal._model_construction import ModelMetaclass
ModuleNotFoundError: No module named 'pydantic._internal'
```

pip freeze versions
`pydantic==1.10.4
tiktokapipy==0.2.0.post1`

**Comment by stolenvw** [comment]
need to fix your requirements got this when updating tiktokapipy
`Requirement already satisfied: pydantic in ./.venv/lib/python3.10/site-packages (from tiktokapipy==0.2.0.post1->-r requirements.txt (line 11)) (1.10.4)`

will try updating it

**Comment by stolenvw** [comment]
updating pydantic to 2.0.2 did fix the issues, Thank you
