### ISSUE TITLE
What is 100004 error code means?

### ISSUE THREAD

**Issue by paweenwat-man** [Russell-Newton/TikTokPy#57]
```
Traceback (most recent call last):
  File "g:\My Project\youtube_poster\main.py", line 16, in <module>
    main()
  File "g:\My Project\youtube_poster\main.py", line 13, in main
    tiktok.scrape()
  File "g:\My Project\youtube_poster\scrapers\tiktok.py", line 28, in scrape
    videos = sorted(challenge.videos.limit(100), key=lambda video: video.create_time, reverse=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\My Project\youtube_poster\env\Lib\site-packages\tiktokapipy\util\deferred_collectors.py", line 60, in __next__
    self._fetch_sync()
  File "G:\My Project\youtube_poster\env\Lib\site-packages\tiktokapipy\util\deferred_collectors.py", line 195, in _fetch_sync
    self._collected_values.append(self._api.video(video.id))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\My Project\youtube_poster\env\Lib\site-packages\tiktokapipy\api.py", line 171, in video
    return self._extract_video_from_response(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\My Project\youtube_poster\env\Lib\site-packages\tiktokapipy\api.py", line 299, in _extract_video_from_response
    f"({ERROR_CODES[response.status_code]})"
        ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: 100004
```

**Comment by Russell-Newton** [comment]
I've never seen this error code before, and I'm not sure what it means. I can't seem to find any documentation online for this.

That being said, you shouldn't get this KeyError anymore in version 0.2.1.
